# Rails の secret_key_base を環境ごとに管理するための設定
# development / test では固定値を使い、CI やローカルでも安定して JWT を検証できるようにする

development:
  secret_key_base: <%= ENV.fetch("SECRET_KEY_BASE", "9d0f8b0d6e6f8bec5e214b0bc33d7968d21d8d6d7a3b2f4c9ecfe3d28c134a8b2d4b04e4e48f5a6c8d7985e0b95ac36c7a1e8ddf5c3aef90ef3a0637652b9a7c") %>

test:
  secret_key_base: 7f2a0e6b1d257ac6db74e0a4f10e8f4a0db4a0fe69c690b4a1c51f4ddda2f7c63b03371b9e6b68f7e4fa0c2135a6c0d2fcab94fdc709d9b67258ae0e64b92d8f

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
